server:
  port: 9090
spring:
  application:
    name: user-rating-test-task
  datasource:
    url: jdbc:postgresql://localhost:5432/userrating
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true